### PR TITLE
Fix typo German instead of English

### PR DESCRIPTION
**Pull request by PaulienVa**

### CODE REVIEW

**Review by lfrancke — APPROVED** [review]

**Comment by lfrancke** [comment]
Thank you for catching this!

**Comment by PaulienVa** [comment]
No pb!

**Comment by lfrancke** [comment]
This is against the 24.3 release branch - we'll also get it fixed on main

Ping @fhennig

**Comment by lfrancke** [comment]
And Felix, please also check why the build fails. Is it because it comes from an external fork?

**Comment by fhennig** [comment]
The build is failing because it isn't running on the main branch. Only the playbook from the main branch can be used to build the documentation.

But thanks for the contribution Paulien! I will move the  change to the main branch as well :)

**Pull request merged**
