### PR TITLE
Document empty string for configOverride

### PR DESCRIPTION
**Pull request by sbernauer**
For https://github.com/orgs/stackabletech/discussions/30

### CODE REVIEW

**Comment by sbernauer** [comment]
@dmasice would you consider this helpful information or is something missing?

**Comment by dmasice** [comment]
@sbernauer Looks good to me, but maybe reference it too from the "Configuration & Environment Overrides" in the operator docs?

**Review by maltesander — APPROVED** [review]
LGTM!

**Comment by sbernauer** [comment]
@dmasice linking needs to be done in every operator individually, so we can mgere this change and add the linking afterards

**Pull request merged**
