### PR TITLE
Add ADR on Platform and Product version LTS strategy

### PR DESCRIPTION
**Pull request by sbernauer**
TODOs:

- [ ] Discuss actual numbers (like **X** months we are going support \<whatever\>)
- [ ] Decide on a policy if users need to go through every platform release line when upgrading, or if they could e.g. go from 23.1 directly to 23.7. We need a decision on how many releases they can skip (e.g. 0).

### CODE REVIEW

**Comment by lfrancke** [comment]
Could you take a look why this does not build? Would be nice to see it in the rendered preview.

**Comment by sbernauer** [comment]
Already fixed it in https://github.com/stackabletech/secret-operator/pull/274, triggered a new run

**Comment by sbernauer** [comment]
Use e.g. https://deploy-preview-401--stackable-docs.netlify.app/home/nightly/contributor/adr/adr028-platform-release-support-policy

**Comment by lfrancke** [comment]
I'm leaning towards closing this PR without merging as we have decided on a lot of policies out-of-band and there's not too much use in documenting it three times.
It'll be added to the docs and the homepage anyway.

@soenkeliebau opinions?

**Comment by soenkeliebau** [comment]
No stromg opinion, but I think we documented why we decided on some things in there that might otherwise get lost?

**Comment by lfrancke** [comment]
IMO not really, no.
So if you have no strong opinion, I'm going to close this in favor of the documentation on the homepage and the docs.

**Comment by sbernauer** [comment]
Works for me

**Comment by sbernauer** [comment]
>  It'll be added to the docs and the homepage anyway.

Is there any link to documentationan of the LTS strategy?

**Comment by lfrancke** [comment]
It's not merged yet. Waiting for review I believe

**Pull request closed without merging**
