### PR TITLE
Don't suggest that users delete CRDs when upgrading

### PR DESCRIPTION
**Pull request by nightkr**
See https://stackable-workspace.slack.com/archives/C031BTE7ZGC/p1683797224359929

Cherry-pick of #405

### CODE REVIEW

**Review by razvan — APPROVED** [review]

**Review by sbernauer — APPROVED** [review]
Thanks!

**Comment by nightkr** [comment]
@fhennig did anything change lately regarding the Antora build?

**Comment by nightkr** [comment]
So this is causing existing objects to become impossible to modify after the upgrade is complete. This is because the new field `status.conditions` is mandatory, but doesn't have a default value. This would have to be fixed in each operator, by adding a default. For example, in nifi-operator:

```diff
diff --git a/rust/crd/src/lib.rs b/rust/crd/src/lib.rs
index 402f8bc..0b8e6b7 100644
--- a/rust/crd/src/lib.rs
+++ b/rust/crd/src/lib.rs
@@ -205,6 +205,7 @@ pub enum NifiRole {
 #[derive(Clone, Debug, Default, Deserialize, JsonSchema, Serialize)]
 pub struct NifiStatus {
     pub deployed_version: Option<String>,
+    #[serde(default)]
     pub conditions: Vec<ClusterCondition>,
 }
```

**Comment by nightkr** [comment]
Ok, this has now been updated from #405.

**Review by adwk67 — APPROVED** [review]

**Pull request merged**
