### PR TITLE
Build documentation for listener-operator

### PR DESCRIPTION
**Pull request by teozkr**

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by lfrancke** [comment]
Forgive my ignorance but: https://docs.stackable.tech/listener-operator/stable/listener.html
This currently doesn't have the version selection dropdown as others do.
Will this happen at the next release?
@teozkr @fhennig

**Comment by teozkr** [comment]
I noticed the same thing, and as I understand it that should be the case...

**Comment by lfrancke** [comment]
I talked to Felix and he agrees, thank you!

**Pull request merged**
